# Generated by Django 5.2 on 2026-04-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_auditlog_details_auditlog_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('status_change', 'Status Change'), ('permissions_change', 'Permissions Change'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approval', 'Approval'), ('export', 'Export'), ('bulk_action', 'Bulk Action')], max_length=100),
        ),
    ]
