# Generated by Django 5.2 on 2026-04-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_auditlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(default='MedHub Virtual Hospital', max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=50)),
                ('fiscal_year_start_month', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_base_url', models.URLField(blank=True, null=True)),
                ('pacs_server', models.CharField(blank=True, max_length=255, null=True)),
                ('lab_middleware_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('enable_pharmacy_integration', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_for_critical', models.BooleanField(default=False)),
                ('email_for_critical', models.BooleanField(default=True)),
                ('daily_department_summary', models.BooleanField(default=False)),
                ('appointment_reminder_hours', models.PositiveIntegerField(default=24)),
            ],
        ),
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_logout_minutes', models.PositiveIntegerField(default=60)),
                ('max_login_attempts', models.PositiveIntegerField(default=3)),
                ('min_password_length', models.PositiveIntegerField(default=8)),
                ('enforce_2fa_for_admins', models.BooleanField(default=False)),
                ('audit_log_retention_days', models.PositiveIntegerField(default=365)),
            ],
        ),
        migrations.DeleteModel(
            name='SystemSetting',
        ),
    ]
