# Generated by Django 5.2 on 2026-04-14 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_generalsettings_integrationsettings_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'permissions': [('export_auditlog', 'Can export audit logs')]},
        ),
    ]
