# Generated by Django 5.2 on 2026-04-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labresult',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('in progress', 'In Progress'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
