# Generated by Django 5.2 on 2026-04-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vital',
            name='diastolic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vital',
            name='systolic',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
