# Generated by Django 5.2 on 2026-04-11 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('specimen', models.CharField(blank=True, max_length=255, null=True)),
                ('tat_hours', models.PositiveIntegerField(help_text='Turnaround time in hours')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('authorization_required', models.BooleanField(default=False)),
                ('cpt_code', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('discontinued', 'Discontinued')], default='active', max_length=20)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicetype')),
            ],
        ),
    ]
