# Generated by Django 5.2 on 2026-04-14 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_role_permissions_remove_user_role_and_more'),
        ('core', '0012_alter_bed_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.department'),
        ),
    ]
