# Generated by Django 5.2 on 2026-04-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('discharged', 'Discharged'), ('deceased', 'Deceased'), ('inactive', 'Inactive')], default='active', max_length=50),
        ),
    ]
