# Generated by Django 5.2 on 2026-04-07 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_department_description_department_types'),
        ('patients', '0003_alter_patient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='core.department'),
        ),
    ]
