# Generated by Django 5.2 on 2026-04-07 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_department_description_department_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='sub_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
