# Generated by Django 5.2 on 2026-04-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_department_sub_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
        migrations.AddField(
            model_name='department',
            name='types',
            field=models.CharField(blank=True, choices=[('clinical', 'Clinical'), ('diagnostic', 'Diagnostic'), ('support', 'Support'), ('administrative', 'Administrative'), ('surgical', 'Surgical'), ('emergency', 'Emergency'), ('pharmacy', 'Pharmacy')], max_length=50, null=True),
        ),
    ]
