# Generated by Django 5.2 on 2026-04-07 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_department_description_department_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='core.ward'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='core.department'),
        ),
    ]
