# Generated by Django 5.2 on 2026-04-08 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_bed_ward_room_bed_room'),
        ('patients', '0004_alter_patient_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beds', to='patients.patient'),
        ),
    ]
