# Generated by Django 5.2 on 2026-04-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_bed_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
