# Generated by Django 5.2 on 2026-04-08 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_bed_number'),
        ('patients', '0004_alter_patient_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beds', to='patients.patient'),
        ),
    ]
